/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f797d67025d0040d25c55723fda9292b)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	FIREBASE_PROJECT_ID: "fraldinha-livre";
	NOTIFICATIONS_ENABLED: "false";
	ADMIN_UID: "KOQclmb5eshfkufioK03ayRh6Fi2";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_ID" | "NOTIFICATIONS_ENABLED" | "ADMIN_UID">> {}
}
